Victor Pugliese Github link:https://github.com/VictorPuglieseManotas e-mail: victor.pugliese@ttu.edu

Acknowledge: The following work has been performed under the supervision of Dr. Ekarit Panacharoensawad, Assistant Professor, Department of Petroleum Engineering, Texas Tech University. Github link: https://github.com/epmmko e-mail: ekarit.panacharoensawad@ttu.edu

The following work has been performed with the collaboration of Dr. Raymond Eghorieta. e-mail: raymond.eghorieta@ttu.edu

# Drift Velocity Analysis

## 1. Introduction

Dimensionles gruoups have been applied by many researchers to estimate the rise velocity of a single bubble moving in liquid in pipe under the influence of gravitational, inertial, viscous and interfacial forces. These are: Reynolds Number, Eotvos number, Viscosyty Number, Bouyancy Reynolds Number and Froud Number.
The objetive of this analysis is to find a model to relate the Froud Number with the rest of dimensionless group. Then, we could use Davies and Taylor (1950) clousure relationship to calculate the drift velocity.

In [1]:
#Libraries used
%matplotlib inline                 
#The output of plotting commands is displayed directly below the code cell that produced it.
import os                          #This module provides a portable way of using operating system dependent functionality
import numpy as np                 #Adds support for large, multi-dimensional arrays and matrices, with a collection of mathematical functions.
import pandas as pd                #Provides data structures and data analysis tools for the Python programming language.
import matplotlib                  #Produces publication quality figures in a variety of hardcopy formats and interactive environments across platforms.
import matplotlib.pyplot as plt    #It is a collection of command style functions that make matplotlib work like MATLAB
import plotly.plotly as py         #A graphing library for making interactive, publication-quality graphs
import plotly.figure_factory as ff
import time
import warnings
warnings.filterwarnings('ignore')  #Never print matching warnings
from six.moves import urllib

## 2. Data Preparation
### 2.1. Load Data
The information is taken from the excel file in VictorPuglieseManotas's repository named Research. In this way, any person could download the raw data: https://github.com/VictorPuglieseManotas/Research/blob/master/Drift_Velocity_Analysis.xlsx

In [2]:
Download="https://github.com/VictorPuglieseManotas/Research/blob/master/Drift_Velocity_Analysis.xlsx"
urllib.request.urlretrieve(Download)                                            #Copy a network object denoted by a URL to a local file
Experimental_Data=pd.read_excel(r"C:\Users\victo\Drift_Velocity_Analysis.xlsx") #Read an Excel table into a pandas DataFrame
Experimental_Data.head()                                                        #Returns the first 5 rows for the object based on position

Inclination [°]  Cos(Angle)  Sin(Angle)  Temperature [C]  \rhoL [kg/m3]  \
0              0.0         1.0         0.0        24.959836     990.895816   
1              0.0         1.0         0.0        21.100000    1000.000000   
2              0.0         1.0         0.0        21.455512     854.350660   
3              0.0         1.0         0.0        32.327778     857.781985   
4              0.0         1.0         0.0        45.000000     873.000000   

   \rhoG [kg/m3]  \muL [Pa.s]  \sigma [N/m] Liquid Type  Diameter [m]  \
0       1.184648     0.000890       0.07280       Water        0.0381   
1       1.200195     0.001000       0.07280       Water        0.0508   
2       1.198746     0.270282       0.03068         Oil        0.0381   
3       1.156061     0.148676       0.03122         Oil        0.0381   
4       1.109992     0.121000       0.02950         Oil        0.0508   

   Drift Velocity [m/s]  Reynolds Number Re  Buoyancy Reynolds R  \
0              0.264870           13.433988         25916.409127   
1              0.350000           21.339473         35833.986900   
2              0.047329            0.007998            73.563521   
3              0.091819            0.027202           134.274008   
4              0.295000            0.137474           258.528549   

   Eotvos Number Eo  Viscosity Number Nmu  Froud Number Fr  
0        193.529742              0.000039         0.433580  
1        347.212354              0.000028         0.496177  
2        395.860019              0.013603         0.077483  
3        390.597034              0.007452         0.150316  
4        747.976210              0.003871         0.418221

Now, we only will use the dimensionless group and the unit vectors:

In [3]:
Experimental_Data=Experimental_Data.drop(Experimental_Data.columns[[0,3,4,5,6,7,8,9,10,11,14]], axis=1)
Experimental_Data.head()

Cos(Angle)  Sin(Angle)  Buoyancy Reynolds R  Eotvos Number Eo  \
0         1.0         0.0         25916.409127        193.529742   
1         1.0         0.0         35833.986900        347.212354   
2         1.0         0.0            73.563521        395.860019   
3         1.0         0.0           134.274008        390.597034   
4         1.0         0.0           258.528549        747.976210   

   Froud Number Fr  
0         0.433580  
1         0.496177  
2         0.077483  
3         0.150316  
4         0.418221

### 2.2. Attribute Combinations

### 2.3. Creating the Train and Test set
The train set will be the experimental data gathered from other researchers. On the other hand, the Test set will be the experimental data obtained by the authors of this document in the Petroleum Engineering Labs in Texas Tech University.

In [4]:
Dimensionless_Labels=Experimental_Data['Froud Number Fr']
Dimensionless_Attributes=Experimental_Data.drop('Froud Number Fr',axis=1)

## 3. Machine Learning Model
### 3.1. Regression Models
#### 3.1.1. SVM Regressor

In [5]:
from sklearn.svm import SVR
svr_rbf_reg = SVR(kernel="rbf",C=100,epsilon=0.1)
svr_rbf_reg

SVR(C=100, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='auto',
  kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

#### 3.1.2. Gradient Boosting Regressor

In [6]:
from sklearn.ensemble import GradientBoostingRegressor
gb_reg = GradientBoostingRegressor(max_depth=3,n_estimators=5,learning_rate=1.0)
gb_reg

GradientBoostingRegressor(alpha=0.9, criterion='friedman_mse', init=None,
             learning_rate=1.0, loss='ls', max_depth=3, max_features=None,
             max_leaf_nodes=None, min_impurity_decrease=0.0,
             min_impurity_split=None, min_samples_leaf=1,
             min_samples_split=2, min_weight_fraction_leaf=0.0,
             n_estimators=5, presort='auto', random_state=None,
             subsample=1.0, verbose=0, warm_start=False)

### 3.2. Training the Model
The problem of Drift Velocity has been addressed. The initial experiment data has been clean and modified in order to have features that are related with the Froud Number. Also, we have splitted the instances. The training set is used in this stage to fit the model parameters. The model disccused is selected because of his potential good performance. However, we will test it using the test set. In the following code, we perform the training procedure, we obtain a measurement of its perfomance (mean_squared_error) and the time required to be fitted and to predict.

In [7]:
from sklearn.metrics import mean_squared_error

for reg in (svr_rbf_reg,gb_reg):
    start = time.time()
    reg.fit(Dimensionless_Attributes,Dimensionless_Labels)
    y_pred=reg.predict(Dimensionless_Attributes)
    print(reg.__class__.__name__,' mean_squared_error: ',mean_squared_error(Dimensionless_Labels,y_pred))
    end = time.time()
    print(reg.__class__.__name__,' Time: ',end - start)

SVR  mean_squared_error:  0.0043449314726771195
SVR  Time:  0.0019567012786865234
GradientBoostingRegressor  mean_squared_error:  0.00039672348694307714
GradientBoostingRegressor  Time:  0.001995563507080078


### 3.2.1. Support Vectors, Dual Coefficient & Intercept

In [8]:
svr_rbf_reg.fit(Dimensionless_Attributes,Dimensionless_Labels)
svr_rbf_reg.support_vectors_

array([[1.00000000e+00, 0.00000000e+00, 7.35635211e+01, 3.95860019e+02],
       [1.00000000e+00, 0.00000000e+00, 1.34274008e+02, 3.90597034e+02],
       [1.00000000e+00, 0.00000000e+00, 9.26176826e+01, 7.57359433e+02],
       [1.00000000e+00, 0.00000000e+00, 6.78347457e+01, 7.59060964e+02],
       [1.00000000e+00, 0.00000000e+00, 5.36562591e+01, 7.60766662e+02],
       [1.00000000e+00, 0.00000000e+00, 4.60316249e+01, 7.61618197e+02],
       [9.84807753e-01, 1.73648178e-01, 2.59164091e+04, 1.93529742e+02],
       [9.92546152e-01, 1.21869343e-01, 7.35635211e+01, 3.95860019e+02],
       [9.84807753e-01, 1.73648178e-01, 7.35635211e+01, 3.95860019e+02],
       [9.92546152e-01, 1.21869343e-01, 1.34489853e+02, 3.90597034e+02],
       [9.84807753e-01, 1.73648178e-01, 1.34238054e+02, 3.90597034e+02],
       [7.66044443e-01, 6.42787610e-01, 3.58339869e+04, 3.47212354e+02],
       [7.66044443e-01, 6.42787610e-01, 2.99411928e+02, 7.44559434e+02],
       [7.66044443e-01, 6.42787610e-01, 1.69671367e

In [9]:
svr_rbf_reg.dual_coef_ 

array([[-3.86266952e+00, -2.75374031e+00, -1.74559094e-03,
        -3.00892059e-02, -5.09797684e-02, -7.54255060e-02,
         4.97882766e-02,  3.63340596e-01,  3.37751054e+00,
         4.28321863e-01,  2.27473276e+00,  1.41628523e-01,
         5.09797684e-02,  3.35899914e-02,  3.86579385e-03,
        -2.63800370e-02, -2.96850609e-02,  1.52051941e-03,
         5.15402312e-02,  6.29947330e-02,  9.13959147e-02,
         2.66290764e-02,  5.61201018e-04, -2.50367588e-02,
        -1.02648032e-01]])

In [10]:
svr_rbf_reg.intercept_

array([0.32571693])

### 3.3. Model Evaluation

### 3.4. Tunning the Model